# Generated by Django 4.1.4 on 2023-01-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greenhouse_app', '0002_remove_token_storage_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_storage',
            name='token_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
