# Generated by Django 4.1.4 on 2023-01-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0003_token_storage_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_storage',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
