# Generated by Django 4.1.3 on 2022-12-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEM_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_real', models.FloatField(verbose_name='z_real')),
                ('z_img', models.FloatField(verbose_name='z_img')),
            ],
        ),
    ]
