# Generated by Django 4.1.3 on 2022-12-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='random_app')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PEM_data',
        ),
    ]
