# Generated by Django 4.1.3 on 2022-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_app', '0002_csv_data_delete_pem_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('fieldA', models.FloatField(verbose_name='fieldA')),
                ('fieldB', models.FloatField(verbose_name='fieldB')),
            ],
        ),
    ]
