# Generated by Django 4.1.3 on 2022-12-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_app', '0003_table_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_data',
        ),
    ]
