# Generated by Django 4.1.3 on 2022-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_app', '0005_remove_csv_data_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_data',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
